services:
  api:
    build:
      context: .  # Dockerfile이 있는 디렉토리 경로
    #    image: sonny0514/music-note-auth:1.0.0
    container_name: gateway-server
    networks:
      - music-network
    environment:
      - TZ=Asia/Seoul
      - LANG=ko_KR.UTF-8
    ports:
      - "8080:8080"

networks:
  music-network:
    external: true