#  포트 랜덤 -> 수정 필
server:
  port: 8081

spring:
  jpa:
    hibernate:
      hbm2ddl.auto: update
      show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  application:
    name: recommend-server

  datasource:
#    url: jdbc:mysql://mysql-db/member?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    url: jdbc:mysql://localhost:3306/member?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: music
    password: note
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    mongodb:
      type:
        uri: mongodb://music:note@localhost:27017/typedb?authSource=admin
#        uri: mongodb://music:note@mongo-db:27017/typedb?authSource=admin
      recommend:
        uri: mongodb://music:note@localhost:27017/recommenddb?authSource=admin
#        uri: mongodb://music:note@mongo-db:27017/recommenddb?authSource=admin


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
#      defaultZone: http://eureka-server:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

jwt:
  secret: music-note-jwt-key


logging:
  level:
    root: INFO
    com.music.note.recommend: INFO