server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          "[/**]": # 모든 경로에 대해 CORS 허용
            allowedOrigins:
              - "http://localhost:5173"
              - "http://localhost:5174"
              - "https://j12a308.p.ssafy.io"
              - "http://127.0.0.1:5500"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: main-route
          uri: lb://main-server
          predicates:
            - Path=/api/main/**
          filters:
            - RewritePath=/api/main/(?<segment>/.*)?, /${segment}

        - id: auth-route
          uri: lb://auth-server
          predicates:
            - Path=/api/auth/**
          filters:
            - RewritePath=/api/auth/(?<segment>/.*)?, /${segment}

        - id: music-route
          uri: lb://music-type-server
          predicates:
            - Path=/api/music/**
          filters:
            - RewritePath=/api/music/(?<segment>/.*)?, /${segment}

        - id: notification-route
          uri: lb://notification-server
          predicates:
            - Path=/api/notifications/**
          filters:
            - RewritePath=/api/notifications/(?<segment>/.*)?, /${segment}

        - id: recommend-route
          uri: lb://recommend-server
          predicates:
            - Path=/api/recommend/**
          filters:
            - RewritePath=/api/recommend/(?<segment>/.*)?, /${segment}

        - id: crawling-route
          uri: lb://music-crawler-consumer
          predicates:
            - Path=/api/crawl/actuator/health
          filters:
            - RewritePath=/api/crawl/(?<segment>/.*)?, /${segment}

        - id: type-consumer-route
          uri: lb://music-type-consumer
          predicates:
            - Path=/api/type/actuator/health, /api/type/weekly-report
          filters:
            - RewritePath=/api/type/(?<segment>/.*)?, /${segment}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
#      defaultZone: http://eureka-server:8761/eureka/