services:
  api:
    build:
      context: .  # Dockerfile이 있는 경로
    container_name: eureka-server
    networks:
      - music-network
    environment:
      - TZ=Asia/Seoul
      - LANG=ko_KR.UTF-8
    ports:
      - "8761:8761"

networks:
  music-network:
    external: true